"""add_telegram_models

Revision ID: 9999f_telegram
Revises: 8253f3746935
Create Date: 2026-04-10 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9999f_telegram_bot'
down_revision: Union[str, Sequence[str], None] = '8253f3746935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vinculation_tokens',
    sa.Column('token', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_vinculation_tokens_token'), 'vinculation_tokens', ['token'], unique=False)
    op.create_index(op.f('ix_vinculation_tokens_user_id'), 'vinculation_tokens', ['user_id'], unique=False)
    op.create_table('alertas_enviadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('tipo_alerta', sa.String(length=50), nullable=False),
    sa.Column('enviada_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_enviadas_id'), 'alertas_enviadas', ['id'], unique=False)
    op.create_index(op.f('ix_alertas_enviadas_task_id'), 'alertas_enviadas', ['task_id'], unique=False)
    op.create_table('redacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('tono', sa.String(length=50), nullable=True),
    sa.Column('input_usuario', sa.Text(), nullable=True),
    sa.Column('output_generado', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redacciones_id'), 'redacciones', ['id'], unique=False)
    op.create_index(op.f('ix_redacciones_user_id'), 'redacciones', ['user_id'], unique=False)
    op.create_table('telegram_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('vinculado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_accounts_id'), 'telegram_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_accounts_telegram_chat_id'), 'telegram_accounts', ['telegram_chat_id'], unique=True)
    op.create_index(op.f('ix_telegram_accounts_user_id'), 'telegram_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_accounts_user_id'), table_name='telegram_accounts')
    op.drop_index(op.f('ix_telegram_accounts_telegram_chat_id'), table_name='telegram_accounts')
    op.drop_index(op.f('ix_telegram_accounts_id'), table_name='telegram_accounts')
    op.drop_table('telegram_accounts')
    op.drop_index(op.f('ix_redacciones_user_id'), table_name='redacciones')
    op.drop_index(op.f('ix_redacciones_id'), table_name='redacciones')
    op.drop_table('redacciones')
    op.drop_index(op.f('ix_alertas_enviadas_task_id'), table_name='alertas_enviadas')
    op.drop_index(op.f('ix_alertas_enviadas_id'), table_name='alertas_enviadas')
    op.drop_table('alertas_enviadas')
    op.drop_index(op.f('ix_vinculation_tokens_user_id'), table_name='vinculation_tokens')
    op.drop_index(op.f('ix_vinculation_tokens_token'), table_name='vinculation_tokens')
    op.drop_table('vinculation_tokens')
    # ### end Alembic commands ###
